[tox]
envlist =
    py37-django{2.0,2.1,2.2}
    py{38,39}-django{2.2,3.0,3.1,3.2}
    py310-django{3.2}

[testenv]
basepython =
    py37: python3.7
    py38: python3.8
    py39: python3.9
    py310: python3.10
deps =
    pytz
    lxml==4.4.0
    Markdown==2.3.1
    docutils==0.11
    template-utils==0.4p2
    jsonfield==1.0.0
    django2.0: django<2.1
    django2.1: django<2.2
    django2.2: django<2.3
    django3.0: django<3.1
    django3.1: django<3.2
    django3.2: django<3.3
setenv =
    PYTHONPATH={toxinidir}
    DJANGO_SETTINGS_MODULE=sample_project.settings
commands = {envpython} {envbindir}/django-admin.py test micropress
