# Generated by Django 2.0.13 on 2025-12-25 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('micropress', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='markup_type',
        ),
    ]
