# Generated by Django 4.2.27 on 2025-12-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micropress', '0002_remove_markup_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='article',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='press',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('press', 'slug'), name='article_slug_per_press'),
        ),
        migrations.AddConstraint(
            model_name='press',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id'), name='press_unique_generic_fk'),
        ),
    ]
