# Generated by Django 4.2.27 on 2025-12-25 22:20

from django.db import migrations, models


def forwards(apps, schema_editor):
    Article = apps.get_model("micropress", "Article")
    for article in Article.objects.all():
        article.extra_data = article._extra_data
        article.save()


class Migration(migrations.Migration):

    dependencies = [
        ('micropress', '0003_uniqueness_constraint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='extra_data',
            new_name='_extra_data',
        ),
        migrations.AddField(
            model_name='article',
            name='extra_data',
            field=models.JSONField(default=dict),
        ),
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='article',
            name='_extra_data',
        ),
    ]
